// Code generated by sqlc; DO NOT EDIT.

package queries

import (
	"context"
	"database/sql"
)

type AuditLog struct {
	ID         int64
	CreatedAt  string
	SourceIP   string
	UserID     sql.NullInt64
	NodeID     sql.NullInt64
	Command    string
	Params     string
	DurationMS int64
	Success    int
	ErrorMsg   string
}

type AuditFilter struct {
	From     string
	To       string
	NodeID   *int64
	Command  string
	SourceIP string
	Page     int
	Limit    int
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg *AuditLog) error {
	_, err := q.db.ExecContext(ctx, `
		INSERT INTO audit_log (created_at, source_ip, user_id, node_id, command, params, duration_ms, success, error_msg)
		VALUES (CURRENT_TIMESTAMP, ?, ?, ?, ?, ?, ?, ?, ?)
	`, arg.SourceIP, arg.UserID, arg.NodeID, arg.Command, arg.Params, arg.DurationMS, arg.Success, arg.ErrorMsg)
	return err
}

func (q *Queries) ListAuditLogs(ctx context.Context, filter *AuditFilter) ([]AuditLog, int, error) {
	where := " WHERE 1=1"
	var filterArgs []interface{}

	if filter.NodeID != nil {
		where += " AND node_id = ?"
		filterArgs = append(filterArgs, *filter.NodeID)
	}
	if filter.Command != "" {
		where += " AND command = ?"
		filterArgs = append(filterArgs, filter.Command)
	}
	if filter.SourceIP != "" {
		where += " AND source_ip = ?"
		filterArgs = append(filterArgs, filter.SourceIP)
	}

	// Count total
	var total int
	countQuery := "SELECT COUNT(*) FROM audit_log" + where
	if err := q.db.QueryRowContext(ctx, countQuery, filterArgs...).Scan(&total); err != nil {
		return nil, 0, err
	}

	// Fetch page
	query := "SELECT id, created_at, source_ip, user_id, node_id, command, params, duration_ms, success, error_msg FROM audit_log" + where + " ORDER BY created_at DESC"
	var args []interface{}
	args = append(args, filterArgs...)

	if filter.Limit > 0 {
		query += " LIMIT ?"
		args = append(args, filter.Limit)
		if filter.Page > 0 {
			query += " OFFSET ?"
			args = append(args, filter.Page*filter.Limit)
		}
	}

	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var logs []AuditLog
	for rows.Next() {
		var l AuditLog
		if err := rows.Scan(&l.ID, &l.CreatedAt, &l.SourceIP, &l.UserID, &l.NodeID,
			&l.Command, &l.Params, &l.DurationMS, &l.Success, &l.ErrorMsg); err != nil {
			return nil, 0, err
		}
		logs = append(logs, l)
	}
	return logs, total, nil
}

func (q *Queries) CleanupAuditLogs(ctx context.Context, olderThan string) (int64, error) {
	result, err := q.db.ExecContext(ctx, `DELETE FROM audit_log WHERE created_at < ?`, olderThan)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
