// Code generated by sqlc; DO NOT EDIT.

package queries

import (
	"context"
	"database/sql"
)

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    string
	LastLogin    sql.NullString
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRowContext(ctx, `
		SELECT id, email, password_hash, role, created_at, last_login
		FROM users WHERE email = ?
	`, email)

	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.Role, &u.CreatedAt, &u.LastLogin)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRowContext(ctx, `
		SELECT id, email, password_hash, role, created_at, last_login
		FROM users WHERE id = ?
	`, id)

	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.Role, &u.CreatedAt, &u.LastLogin)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

func (q *Queries) CreateUser(ctx context.Context, arg *User) (*User, error) {
	result, err := q.db.ExecContext(ctx, `
		INSERT INTO users (email, password_hash, role, created_at)
		VALUES (?, ?, ?, CURRENT_TIMESTAMP)
	`, arg.Email, arg.PasswordHash, arg.Role)
	if err != nil {
		return nil, err
	}

	id, err := result.LastInsertId()
	if err != nil {
		return nil, err
	}
	return q.GetUserByID(ctx, id)
}

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, `DELETE FROM users WHERE id = ?`, id)
	return err
}

func (q *Queries) UpdateLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, `UPDATE users SET last_login = CURRENT_TIMESTAMP WHERE id = ?`, id)
	return err
}

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, `
		SELECT id, email, password_hash, role, created_at, last_login
		FROM users ORDER BY email
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.Role, &u.CreatedAt, &u.LastLogin); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return users, nil
}