// Code generated by sqlc; DO NOT EDIT.

package queries

import (
	"context"
	"database/sql"
)

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    string
	LastLogin    sql.NullString
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRowContext(ctx, `
		SELECT id, email, password_hash, created_at, last_login
		FROM users WHERE email = ?
	`, email)

	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt, &u.LastLogin)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRowContext(ctx, `
		SELECT id, email, password_hash, created_at, last_login
		FROM users WHERE id = ?
	`, id)

	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt, &u.LastLogin)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

func (q *Queries) UpdateLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, `UPDATE users SET last_login = CURRENT_TIMESTAMP WHERE id = ?`, id)
	return err
}

func (q *Queries) UpdateUser(ctx context.Context, id int64, email, passwordHash string) error {
	_, err := q.db.ExecContext(ctx, `
		UPDATE users SET email = ?, password_hash = ? WHERE id = ?
	`, email, passwordHash, id)
	return err
}
