// Hand-maintained. NOT generated by sqlc — do not add a matching
// internal/store/sql/*.sql source expecting this file to be regenerated.
//
// There is no query source for this file: internal/store/sql/ holds only
// schema.sql, so `sqlc generate` has nothing to produce these methods from. The
// header this comment replaces said "Code generated by sqlc; DO NOT EDIT" and was
// simply false.
//
// Unlike audit.sql.go, every query here is static SQL, so these methods COULD be
// sqlc-generated if a query source were added — unlike the dynamic WHERE builder
// in ListAuditLogs, which sqlc cannot express. If regeneration is ever wanted
// here, add the .sql source and let sqlc overwrite this file; that would be the
// correct fix, and it is the mistake this header invited someone to make blindly.
package queries

import (
	"context"
	"database/sql"
)

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    string
	LastLogin    sql.NullString
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRowContext(ctx, `
		SELECT id, email, password_hash, created_at, last_login
		FROM users WHERE email = ?
	`, email)

	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt, &u.LastLogin)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRowContext(ctx, `
		SELECT id, email, password_hash, created_at, last_login
		FROM users WHERE id = ?
	`, id)

	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.CreatedAt, &u.LastLogin)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

func (q *Queries) UpdateLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, `UPDATE users SET last_login = CURRENT_TIMESTAMP WHERE id = ?`, id)
	return err
}

func (q *Queries) UpdateUser(ctx context.Context, id int64, email, passwordHash string) error {
	_, err := q.db.ExecContext(ctx, `
		UPDATE users SET email = ?, password_hash = ? WHERE id = ?
	`, email, passwordHash, id)
	return err
}
